DEPARTMENTS = {
    'hrd': {
        'department_name': 'HUMAN RESOURCE DEVELOPMENT DEPARTMENT',
        'title_lines': ['HUMAN RESOURCE DEVELOPMENT', 'DEPARTMENT'],
        'quote': 'Work Hard in Silence, Let Your Succeed be Noise',
        'logo_file': 'img/logo_hrd.svg',
        'greeting_department': 'HRD',
        'welcome_department': 'HRD',
    },
    'internal': {
        'department_name': 'INTERNAL AFFAIRS DEPARTMENT',
        'title_lines': ['INTERNAL AFFAIRS DEPARTMENT'],
        'quote': 'Internal Kuat, ALSA Hebat',
        'logo_file': 'img/logo_internal.svg',
        'greeting_department': 'Internal',
        'welcome_department': 'Internal Affairs',
    },
    'external': {
        'department_name': 'EXTERNAL AFFAIRS DEPARTMENT',
        'title_lines': ['EXTERNAL AFFAIRS DEPARTMENT'],
        'quote': 'Give More Contribution, in ALSA to Relation',
        'logo_file': 'img/logo_external.svg',
        'greeting_department': 'External',
        'welcome_department': 'External',
    },
    'apr': {
        'department_name': 'ALUMNI & PUBLIC RELATION DEPARTMENT',
        'title_lines': ['ALUMNI & PUBLIC RELATION', 'DEPARTMENT'],
        'quote': 'We Build, We Connect, We Keep',
        'logo_file': 'img/logo_pr.svg',
        'greeting_department': 'APR',
        'welcome_department': 'APR',
    },
    'tim': {
        'department_name': 'TECHNOLOGY, INFORMATION, MULTIMEDIA DEPARTMENT',
        'title_lines': ['TECHNOLOGY, INFORMATION,', 'MULTIMEDIA DEPARTMENT'],
        'quote': 'Alone We Can Do So Little, Together We Can Do So Much',
        'logo_file': 'img/logo_mulmed.svg',
        'greeting_department': 'TIM',
        'welcome_department': 'TIM',
    },
    'mcd': {
        'department_name': 'MOOT COURT DEPARTMENT',
        'title_lines': ['MOOT COURT DEPARTMENT'],
        'quote': 'In Moot Court We Meet, in Moot Court We Unite!',
        'logo_file': 'img/logo_mcd.svg',
        'greeting_department': 'Moot Court',
        'welcome_department': 'Moot Court',
    },
    'lrc': {
        'department_name': 'LEGAL RESEARCH & COUNSELING DEPARTMENT',
        'title_lines': ['LEGAL RESEARCH & COUNSELING', 'DEPARTMENT'],
        'quote': 'We Research, We Share',
        'logo_file': 'img/logo_lrc.svg',
        'greeting_department': 'LRC',
        'welcome_department': 'LRC',
    },
    'english': {
        'department_name': 'ENGLISH DEPARTMENT',
        'title_lines': ['ENGLISH DEPARTMENT'],
        'quote': 'In ALSA We Trust, In English We Crush, English Awesome!',
        'logo_file': 'img/logo_english.svg',
        'greeting_department': 'English',
        'welcome_department': 'English',
    },
    'secretariat': {
        'department_name': 'SECRETARIAT DEPARTMENT',
        'title_lines': ['SECRETARIAT DEPARTMENT'],
        'quote': 'There is No Place Like Home, and Home is Secretariat',
        'logo_file': 'img/logo_secretariat.svg',
        'greeting_department': 'Secretariat',
        'welcome_department': 'Secretariat',
    },
    'funding': {
        'department_name': 'FUNDING DEPARTMENT',
        'title_lines': ['FUNDING DEPARTMENT'],
        'quote': 'Money is Not Everything, But Everything Needs Money',
        'logo_file': 'img/logo_funding.svg',
        'greeting_department': 'Funding',
        'welcome_department': 'Funding',
    },
}

DEPARTMENT_CHOICES = [(slug, meta['department_name']) for slug, meta in DEPARTMENTS.items()]

DEPARTMENT_NAME_TO_SLUG = {
    'Human Resource Development Department': 'hrd',
    'Internal Affairs Department': 'internal',
    'External Affairs Department': 'external',
    'Alumni and Public Relation Department': 'apr',
    'Alumni and Public Relation': 'apr',
    'Technology, Information, and Multimedia Department': 'tim',
    'Moot Court Department': 'mcd',
    'Legal Research and Counseling Department': 'lrc',
    'English Department': 'english',
    'Secretariat Department': 'secretariat',
    'Funding Department': 'funding',
    'hrd': 'hrd',
    'internal': 'internal',
    'external': 'external',
    'apr': 'apr',
    'tim': 'tim',
    'mcd': 'mcd',
    'lrc': 'lrc',
    'english': 'english',
    'secretariat': 'secretariat',
    'funding': 'funding',
}
