# Generated by Django 6.0.4 on 2026-05-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('hrd', 'HUMAN RESOURCE DEVELOPMENT DEPARTMENT'), ('internal', 'INTERNAL AFFAIRS DEPARTMENT'), ('external', 'EXTERNAL AFFAIRS DEPARTMENT'), ('apr', 'ALUMNI & PUBLIC RELATION DEPARTMENT'), ('tim', 'TECHNOLOGY, INFORMATION, MULTIMEDIA DEPARTMENT'), ('mcd', 'MOOT COURT DEPARTMENT'), ('lrc', 'LEGAL RESEARCH & COUNSELING DEPARTMENT'), ('english', 'ENGLISH DEPARTMENT'), ('secretariat', 'SECRETARIAT DEPARTMENT'), ('funding', 'FUNDING DEPARTMENT')], max_length=32)),
            ],
            options={
                'ordering': ['nim'],
            },
        ),
    ]
